#############################################################################
# Makefile for building: BattagliaNavale.app/Contents/MacOS/BattagliaNavale
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  BattagliaNavale/BattagliaNavale.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile BattagliaNavale/BattagliaNavale.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -IBattagliaNavale -I. -IBattagliaNavale -I/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I. -I/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.15.0/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BattagliaNavale1.0.0
DISTDIR = /Users/Simone/Desktop/programmi\ c++/.tmp/BattagliaNavale1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.15.0/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = BattagliaNavale/buttonb.cpp \
		BattagliaNavale/computer.cpp \
		BattagliaNavale/controller.cpp \
		BattagliaNavale/giocatore.cpp \
		BattagliaNavale/main.cpp \
		BattagliaNavale/modellogioco.cpp \
		BattagliaNavale/modelloposizione.cpp \
		BattagliaNavale/moveexception.cpp \
		BattagliaNavale/nave.cpp \
		BattagliaNavale/naveassalto.cpp \
		BattagliaNavale/navecorazzata.cpp \
		BattagliaNavale/navecrociere.cpp \
		BattagliaNavale/naveportaerei.cpp \
		BattagliaNavale/vistagioco.cpp \
		BattagliaNavale/vistaposizione.cpp qrc_Risorse.cpp \
		moc_buttonb.cpp \
		moc_controller.cpp \
		moc_vistagioco.cpp \
		moc_vistaposizione.cpp
OBJECTS       = buttonb.o \
		computer.o \
		controller.o \
		giocatore.o \
		main.o \
		modellogioco.o \
		modelloposizione.o \
		moveexception.o \
		nave.o \
		naveassalto.o \
		navecorazzata.o \
		navecrociere.o \
		naveportaerei.o \
		vistagioco.o \
		vistaposizione.o \
		qrc_Risorse.o \
		moc_buttonb.o \
		moc_controller.o \
		moc_vistagioco.o \
		moc_vistaposizione.o
DIST          = /usr/local/Cellar/qt/5.15.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/spec_post.prf \
		BattagliaNavale/.qmake.stash \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/lex.prf \
		BattagliaNavale/BattagliaNavale/BattagliaNavale.pro BattagliaNavale/buttonb.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/controller.h \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/model.h \
		BattagliaNavale/modellogioco.h \
		BattagliaNavale/modelloposizione.h \
		BattagliaNavale/moveexception.h \
		BattagliaNavale/nave.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/ui_schermata.h \
		BattagliaNavale/vistagioco.h \
		BattagliaNavale/vistaposizione.h BattagliaNavale/buttonb.cpp \
		BattagliaNavale/computer.cpp \
		BattagliaNavale/controller.cpp \
		BattagliaNavale/giocatore.cpp \
		BattagliaNavale/main.cpp \
		BattagliaNavale/modellogioco.cpp \
		BattagliaNavale/modelloposizione.cpp \
		BattagliaNavale/moveexception.cpp \
		BattagliaNavale/nave.cpp \
		BattagliaNavale/naveassalto.cpp \
		BattagliaNavale/navecorazzata.cpp \
		BattagliaNavale/navecrociere.cpp \
		BattagliaNavale/naveportaerei.cpp \
		BattagliaNavale/vistagioco.cpp \
		BattagliaNavale/vistaposizione.cpp
QMAKE_TARGET  = BattagliaNavale
DESTDIR       = 
TARGET        = BattagliaNavale.app/Contents/MacOS/BattagliaNavale

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/Simone/Desktop/programmi c++/BattagliaNavale/BattagliaNavale.pro


include /usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

BattagliaNavale.app/Contents/MacOS/BattagliaNavale: ui_schermata.h $(OBJECTS)  
	@test -d BattagliaNavale.app/Contents/MacOS/ || mkdir -p BattagliaNavale.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BattagliaNavale/BattagliaNavale.pro /usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.15.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.0/mkspecs/features/lex.prf \
		BattagliaNavale/BattagliaNavale.pro \
		BattagliaNavale/Risorse.qrc \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile BattagliaNavale/BattagliaNavale.pro
/usr/local/Cellar/qt/5.15.0/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.15.0/mkspecs/features/lex.prf:
BattagliaNavale/BattagliaNavale.pro:
BattagliaNavale/Risorse.qrc:
/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BattagliaNavale/BattagliaNavale.pro

qmake_all: FORCE

BattagliaNavale.app/Contents/PkgInfo: 
	@test -d BattagliaNavale.app/Contents || mkdir -p BattagliaNavale.app/Contents
	@$(DEL_FILE) BattagliaNavale.app/Contents/PkgInfo
	@echo "APPL????" > BattagliaNavale.app/Contents/PkgInfo
BattagliaNavale.app/Contents/Resources/empty.lproj: 
	@test -d BattagliaNavale.app/Contents/Resources || mkdir -p BattagliaNavale.app/Contents/Resources
	@touch BattagliaNavale.app/Contents/Resources/empty.lproj
	
BattagliaNavale.app/Contents/Info.plist: 
	@test -d BattagliaNavale.app/Contents || mkdir -p BattagliaNavale.app/Contents
	@$(DEL_FILE) BattagliaNavale.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,Simone.BattagliaNavale,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},Simone.BattagliaNavale,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,BattagliaNavale,g" -e "s,@LIBRARY@,BattagliaNavale,g" -e "s,\$${EXECUTABLE_NAME},BattagliaNavale,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang/Info.plist.app >BattagliaNavale.app/Contents/Info.plist

all: Makefile \
		BattagliaNavale.app/Contents/PkgInfo \
		BattagliaNavale.app/Contents/Resources/empty.lproj \
		BattagliaNavale.app/Contents/Info.plist BattagliaNavale.app/Contents/MacOS/BattagliaNavale

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents BattagliaNavale/Risorse.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.15.0/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents BattagliaNavale/buttonb.h BattagliaNavale/computer.h BattagliaNavale/controller.h BattagliaNavale/dimensione.h BattagliaNavale/giocatore.h BattagliaNavale/model.h BattagliaNavale/modellogioco.h BattagliaNavale/modelloposizione.h BattagliaNavale/moveexception.h BattagliaNavale/nave.h BattagliaNavale/naveassalto.h BattagliaNavale/navecorazzata.h BattagliaNavale/navecrociere.h BattagliaNavale/naveportaerei.h BattagliaNavale/ui_schermata.h BattagliaNavale/vistagioco.h BattagliaNavale/vistaposizione.h $(DISTDIR)/
	$(COPY_FILE) --parents BattagliaNavale/buttonb.cpp BattagliaNavale/computer.cpp BattagliaNavale/controller.cpp BattagliaNavale/giocatore.cpp BattagliaNavale/main.cpp BattagliaNavale/modellogioco.cpp BattagliaNavale/modelloposizione.cpp BattagliaNavale/moveexception.cpp BattagliaNavale/nave.cpp BattagliaNavale/naveassalto.cpp BattagliaNavale/navecorazzata.cpp BattagliaNavale/navecrociere.cpp BattagliaNavale/naveportaerei.cpp BattagliaNavale/vistagioco.cpp BattagliaNavale/vistaposizione.cpp $(DISTDIR)/
	$(COPY_FILE) --parents BattagliaNavale/schermata.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r BattagliaNavale.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Risorse.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Risorse.cpp
qrc_Risorse.cpp: BattagliaNavale/Risorse.qrc \
		/usr/local/Cellar/qt/5.15.0/bin/rcc \
		BattagliaNavale/risorse/quadratoRosso.png \
		BattagliaNavale/risorse/XMancata.jpg \
		BattagliaNavale/risorse/Affondata.png \
		BattagliaNavale/risorse/style.css
	/usr/local/Cellar/qt/5.15.0/bin/rcc -name Risorse BattagliaNavale/Risorse.qrc -o qrc_Risorse.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.15.0/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.15.0/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_buttonb.cpp moc_controller.cpp moc_vistagioco.cpp moc_vistaposizione.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_buttonb.cpp moc_controller.cpp moc_vistagioco.cpp moc_vistaposizione.cpp
moc_buttonb.cpp: BattagliaNavale/buttonb.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.0/bin/moc
	/usr/local/Cellar/qt/5.15.0/bin/moc $(DEFINES) --include '/Users/Simone/Desktop/programmi c++/moc_predefs.h' -I/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.0/lib BattagliaNavale/buttonb.h -o moc_buttonb.cpp

moc_controller.cpp: BattagliaNavale/controller.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qobject.h \
		BattagliaNavale/modellogioco.h \
		BattagliaNavale/model.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/moveexception.h \
		BattagliaNavale/modelloposizione.h \
		BattagliaNavale/vistagioco.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLayoutItem \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qstring.h \
		BattagliaNavale/vistaposizione.h \
		BattagliaNavale/buttonb.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.0/bin/moc
	/usr/local/Cellar/qt/5.15.0/bin/moc $(DEFINES) --include '/Users/Simone/Desktop/programmi c++/moc_predefs.h' -I/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.0/lib BattagliaNavale/controller.h -o moc_controller.cpp

moc_vistagioco.cpp: BattagliaNavale/vistagioco.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLayoutItem \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qstring.h \
		BattagliaNavale/vistaposizione.h \
		BattagliaNavale/buttonb.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.0/bin/moc
	/usr/local/Cellar/qt/5.15.0/bin/moc $(DEFINES) --include '/Users/Simone/Desktop/programmi c++/moc_predefs.h' -I/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.0/lib BattagliaNavale/vistagioco.h -o moc_vistagioco.cpp

moc_vistaposizione.cpp: BattagliaNavale/vistaposizione.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLayoutItem \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qstring.h \
		BattagliaNavale/buttonb.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.0/bin/moc
	/usr/local/Cellar/qt/5.15.0/bin/moc $(DEFINES) --include '/Users/Simone/Desktop/programmi c++/moc_predefs.h' -I/usr/local/Cellar/qt/5.15.0/mkspecs/macx-clang -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I'/Users/Simone/Desktop/programmi c++/BattagliaNavale' -I/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.0/lib BattagliaNavale/vistaposizione.h -o moc_vistaposizione.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_schermata.h
compiler_uic_clean:
	-$(DEL_FILE) ui_schermata.h
ui_schermata.h: BattagliaNavale/schermata.ui \
		/usr/local/Cellar/qt/5.15.0/bin/uic
	/usr/local/Cellar/qt/5.15.0/bin/uic BattagliaNavale/schermata.ui -o ui_schermata.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

buttonb.o: BattagliaNavale/buttonb.cpp BattagliaNavale/buttonb.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buttonb.o BattagliaNavale/buttonb.cpp

computer.o: BattagliaNavale/computer.cpp BattagliaNavale/computer.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computer.o BattagliaNavale/computer.cpp

controller.o: BattagliaNavale/controller.cpp BattagliaNavale/controller.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qobject.h \
		BattagliaNavale/modellogioco.h \
		BattagliaNavale/model.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/moveexception.h \
		BattagliaNavale/modelloposizione.h \
		BattagliaNavale/vistagioco.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLayoutItem \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qstring.h \
		BattagliaNavale/vistaposizione.h \
		BattagliaNavale/buttonb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o BattagliaNavale/controller.cpp

giocatore.o: BattagliaNavale/giocatore.cpp BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o giocatore.o BattagliaNavale/giocatore.cpp

main.o: BattagliaNavale/main.cpp /usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qapplication.h \
		BattagliaNavale/vistaposizione.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLayoutItem \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qstring.h \
		BattagliaNavale/buttonb.h \
		BattagliaNavale/vistagioco.h \
		BattagliaNavale/controller.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qobject.h \
		BattagliaNavale/modellogioco.h \
		BattagliaNavale/model.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/moveexception.h \
		BattagliaNavale/modelloposizione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o BattagliaNavale/main.cpp

modellogioco.o: BattagliaNavale/modellogioco.cpp BattagliaNavale/modellogioco.h \
		BattagliaNavale/model.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/moveexception.h \
		BattagliaNavale/modelloposizione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modellogioco.o BattagliaNavale/modellogioco.cpp

modelloposizione.o: BattagliaNavale/modelloposizione.cpp BattagliaNavale/modelloposizione.h \
		BattagliaNavale/model.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/moveexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelloposizione.o BattagliaNavale/modelloposizione.cpp

moveexception.o: BattagliaNavale/moveexception.cpp BattagliaNavale/moveexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moveexception.o BattagliaNavale/moveexception.cpp

nave.o: BattagliaNavale/nave.cpp BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nave.o BattagliaNavale/nave.cpp

naveassalto.o: BattagliaNavale/naveassalto.cpp BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o naveassalto.o BattagliaNavale/naveassalto.cpp

navecorazzata.o: BattagliaNavale/navecorazzata.cpp BattagliaNavale/navecorazzata.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navecorazzata.o BattagliaNavale/navecorazzata.cpp

navecrociere.o: BattagliaNavale/navecrociere.cpp BattagliaNavale/navecrociere.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navecrociere.o BattagliaNavale/navecrociere.cpp

naveportaerei.o: BattagliaNavale/naveportaerei.cpp BattagliaNavale/naveportaerei.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o naveportaerei.o BattagliaNavale/naveportaerei.cpp

vistagioco.o: BattagliaNavale/vistagioco.cpp BattagliaNavale/vistagioco.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLayoutItem \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qstring.h \
		BattagliaNavale/vistaposizione.h \
		BattagliaNavale/buttonb.h \
		BattagliaNavale/controller.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qobject.h \
		BattagliaNavale/modellogioco.h \
		BattagliaNavale/model.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/moveexception.h \
		BattagliaNavale/modelloposizione.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vistagioco.o BattagliaNavale/vistagioco.cpp

vistaposizione.o: BattagliaNavale/vistaposizione.cpp BattagliaNavale/vistaposizione.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/QLayoutItem \
		/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qstring.h \
		BattagliaNavale/buttonb.h \
		BattagliaNavale/controller.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qobject.h \
		BattagliaNavale/modellogioco.h \
		BattagliaNavale/model.h \
		BattagliaNavale/giocatore.h \
		BattagliaNavale/naveassalto.h \
		BattagliaNavale/nave.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator64 \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/QRandomGenerator \
		BattagliaNavale/dimensione.h \
		BattagliaNavale/navecorazzata.h \
		BattagliaNavale/navecrociere.h \
		BattagliaNavale/naveportaerei.h \
		BattagliaNavale/computer.h \
		BattagliaNavale/moveexception.h \
		BattagliaNavale/modelloposizione.h \
		BattagliaNavale/vistagioco.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vistaposizione.o BattagliaNavale/vistaposizione.cpp

qrc_Risorse.o: qrc_Risorse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Risorse.o qrc_Risorse.cpp

moc_buttonb.o: moc_buttonb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buttonb.o moc_buttonb.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

moc_vistagioco.o: moc_vistagioco.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vistagioco.o moc_vistagioco.cpp

moc_vistaposizione.o: moc_vistaposizione.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vistaposizione.o moc_vistaposizione.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

